In [1]:
!pip install pyvi gensim polars

Collecting pyvi
  Downloading pyvi-0.1.1-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pyvi) (1.6.1)
Collecting sklearn-crfsuite (from pyvi)
  Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars) (1.35.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyvi) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyvi) (3.6.0)
Collecting python-crfsuite>=0.9.7 (from sklearn-crfsuite->pyvi)
  Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: tabulate>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from sklearn-crfsuite->pyvi) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /usr/local/lib/python3.12/dist-packages (from sklearn-crfsuite->pyvi) (4.67.3)
Downloading pyvi-0.1.1-py2.py3-none-any.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 104.3 MB/s eta 0:00:00
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 78.0 MB/s eta 0:00:00
Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl (10 kB)
Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 78.2 MB/s eta 0:00:00
Installing collected packages: python-crfsuite, gensim, sklearn-crfsuite, pyvi
Successfully installed gensim-4.4.0 python-crfsuite-0.9.12 pyvi-0.1.1 sklearn-crfsuite-0.5.0

In [2]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!unzip /content/drive/MyDrive/Database/NLP/Embedding_Weather_ForeCast.zip

Archive:  /content/drive/MyDrive/Database/NLP/Embedding_Weather_ForeCast.zip
  inflating: Dataset_articles_NoID.csv

In [4]:
import polars as pl
import torch
import uuid
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.25.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence_transformers) (1.4.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (0.1.2)

In [5]:
df = (pl.read_csv('/content/Dataset_articles_NoID.csv'))

In [6]:
display(df)

shape: (313_320, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ URL        ┆ Title      ┆ Summary    ┆ Contents  ┆ Date      ┆ Author(s) ┆ Category  ┆ Tags      │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ str        ┆ str       ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ https://la ┆ Thông tin  ┆ Lâm Đồng   ┆ Những ngà ┆ Thứ sáu,  ┆ Phương    ┆ Bất động  ┆ ['Lâm     │
│ odong.vn/b ┆ “Ngọc      ┆ - Lãnh đạo ┆ y vừa qua ┆ 20/05/202 ┆ Nhiên     ┆ sản       ┆ Đồng',    │
│ at-dong-sa ┆ Trinh mua  ┆ thành phố  ┆ , trên tr ┆ 2 08:56   ┆           ┆           ┆ 'Ngọc     │
│ …          ┆ đất …      ┆ …          ┆ ang…      ┆ (GMT…     ┆           ┆           ┆ Trinh',   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 'Ch…      │
│ https://la ┆ Lỗ hổng    ┆ TPHCM -    ┆ Theo      ┆ Thứ sáu,  ┆ Gia Miêu  ┆ Bất động  ┆ ['Thủ     │
│ odong.vn/b ┆ trong việc ┆ Việc không ┆ thông tin ┆ 20/05/202 ┆           ┆ sản       ┆ Thiêm',   │
│ at-dong-sa ┆ thẩm tra   ┆ thể cưỡng  ┆ từ Cục    ┆ 2 08:10   ┆           ┆           ┆ 'Đấu giá  │
│ …          ┆ nă…        ┆ c…         ┆ Thuế TP.… ┆ (GMT…     ┆           ┆           ┆ đất']     │
│ https://la ┆ Sớm hoàn   ┆ Hiện trên  ┆ CNLĐ mong ┆ Thứ sáu,  ┆ NGUYỄN    ┆ Bất động  ┆ ['Dự án', │
│ odong.vn/b ┆ thiện các  ┆ địa bàn    ┆ muốn sớm  ┆ 20/05/202 ┆ TRƯỜNG    ┆ sản       ┆ 'Nhà ở xã │
│ at-dong-sa ┆ dự án nhà  ┆ tỉnh Ninh  ┆ được tiếp ┆ 2 07:47   ┆           ┆           ┆ hội', 'Dự │
│ …          ┆ ở…         ┆ Bì…        ┆ c…        ┆ (GMT…     ┆           ┆           ┆ …         │
│ https://la ┆ Chi tiết   ┆ Hoàn công  ┆ Hoàn công ┆ Thứ sáu,  ┆ Kim Nhung ┆ Bất động  ┆ ['Giấy    │
│ odong.vn/b ┆ hồ sơ hoàn ┆ nhà ở với  ┆ nhà ở là  ┆ 20/05/202 ┆ (T/H)     ┆ sản       ┆ phép xây  │
│ at-dong-sa ┆ công nhà   ┆ ý nghĩa    ┆ một thủ   ┆ 2 06:44   ┆           ┆           ┆ dựng',    │
│ …          ┆ ở…         ┆ là…        ┆ tục…      ┆ (GMT…     ┆           ┆           ┆ 'Hồ sơ …  │
│ https://la ┆ Khởi tạo   ┆ Có rất     ┆ Đi dọc    ┆ Thứ năm,  ┆ Huyền     ┆ Bất động  ┆ ['An Quý  │
│ odong.vn/b ┆ không gian ┆ nhiều lý   ┆ đường Lê  ┆ 19/05/202 ┆ Nguyễn    ┆ sản       ┆ Villa']   │
│ at-dong-sa ┆ sống đẳng  ┆ do khiến   ┆ Văn Lương ┆ 2 15:30   ┆           ┆           ┆           │
│ …          ┆ …          ┆ những…     ┆ kéo …     ┆ (GMT…     ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ https://la ┆ Bà lão mù  ┆ Bà Dương   ┆ null      ┆ Thứ tư,   ┆ Lâm Hưng  ┆ Tấm Lòng  ┆ ['Chất    │
│ odong.vn/t ┆ nuôi con,  ┆ Thị Tuyết  ┆           ┆ 14/08/201 ┆ Thơ       ┆ Vàng      ┆ độc']     │
│ lv-canh-do ┆ cháu bị    ┆ ở thị trấn ┆           ┆ 3 06:57   ┆           ┆           ┆           │
│ …          ┆ ản…        ┆ …          ┆           ┆ (GMT+…    ┆           ┆           ┆           │
│ https://la ┆ Trao 100   ┆ Ngày 25.7, ┆ null      ┆ Thứ sáu,  ┆ Lưu Phong ┆ Tin hoạt  ┆ ['Phú     │
│ odong.vn/h ┆ triệu đồng ┆ Đại diện   ┆           ┆ 26/07/201 ┆           ┆ động      ┆ Yên']     │
│ o-tro-bao- ┆ cho ngư    ┆ Chương     ┆           ┆ 3 09:03   ┆           ┆           ┆           │
│ …          ┆ dâ…        ┆ trì…       ┆           ┆ (GMT…     ┆           ┆           ┆           │
│ https://la ┆ Trao 2     ┆ Ngày 17.7, ┆ null      ┆ Thứ năm,  ┆ Bảo Duy   ┆ Tin hoạt  ┆ ['Mái ấm  │
│ odong.vn/g ┆ “Mái ấm    ┆ lãnh đạo   ┆           ┆ 18/07/201 ┆           ┆ động      ┆ Công      │
│ iup-do-cac ┆ công đoàn” ┆ Quỹ TLV    ┆           ┆ 3 07:37   ┆           ┆           ┆ đoàn',    │
│ …          ┆ tới …      ┆ La…        ┆           ┆ (GMT…     ┆           ┆           ┆ 'Bắc      │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Gian…     │
│ https://la ┆ Hãy giúp   ┆ Nhà báo    ┆ null      ┆ Thứ năm,  ┆ Hoàng     ┆ Tấm Lòng  ┆ ['Nhà     │
│ odong.vn/t ┆ đỡ một nhà ┆ Trần Đình  ┆           ┆ 20/06/201 ┆ Mạnh -    ┆ Vàng      ┆ báo',     │
│ lv-canh-do ┆ báo cần    ┆ Chính (tức ┆           ┆ 3 07:28   ┆ Phạm Tùng ┆           ┆ 'Báo']    │
│ …          ┆ th…        ┆ T…         ┆           ┆ (GMT…     ┆           ┆           ┆           │
│ https://la ┆ “Người đàn ┆ Ngày 2.6,  ┆ null      ┆ Chủ nhật, ┆ Đình Văn  ┆ Quỹ TLV   ┆ ['Quảng   │
│ odong.vn/t ┆ bà quỷ ám” ┆ khi nhận   ┆           ┆ 16/06/201 ┆ - Bảo Duy ┆           ┆ Trị']     │
│ lv-nhat-ky ┆ ở Quảng …  ┆ được số    ┆           ┆ 3 19:42   ┆           ┆           ┆           │
│ …          ┆            ┆ tiề…       ┆           ┆ (GM…      ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [7]:
print(df.filter(pl.col('Contents') != 'null').height)

307763

In [8]:
df_clean = (
    df
    .filter(pl.col('Contents') != 'null')
)
df = (
    df_clean
    .with_row_index(name="id")
    .select(
        pl.format("doc_{}", pl.col("id").alias("id")),
        pl.col("Contents").alias("content")
    )
)

In [9]:
import json
from sentence_transformers import SentenceTransformer
from torch.utils.data import DataLoader

In [10]:
model_name = "bkai-foundation-models/vietnamese-bi-encoder"
print(f"Downloading {model_name}")
model = SentenceTransformer(model_name)

Downloading bkai-foundation-models/vietnamese-bi-encoder

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

In [19]:
texts = df.get_column("content").to_list()
ids = df.get_column("id").to_list()
texts = texts[:1000]
print(len(texts))

1000

In [22]:
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
model_name = "bkai-foundation-models/vietnamese-bi-encoder"
print(f"Đang tải model {model_name}...")
model = SentenceTransformer(model_name)
model.max_seq_length = 256
train_examples = []
for text in texts:
    if isinstance(text, str) and len(text.strip()) > 0:
        train_examples.append(InputExample(texts=[text, text]))
train_dataloader = DataLoader(train_examples, shuffle = True, batch_size = 16)
train_loss = losses.MultipleNegativesRankingLoss(model)
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=1,
    warmup_steps=100,
    show_progress_bar=True,
    output_path="./my_trained_model"
)

Đang tải model bkai-foundation-models/vietnamese-bi-encoder...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
model = SentenceTransformer("./my_trained_model")
corpus_embeddings = model.encode(texts, batch_size=32, convert_to_tensor=True, show_progress_bar=True)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [28]:
from sentence_transformers import util
def query(query, top_k = 5):
  query_embedding = model.encode(query, convert_to_tensor=True)
  hits = util.semantic_search(query_embedding, corpus_embeddings, top_k=top_k)
  top_results = hits[0]
  for i, hit in enumerate(top_results):
        vitri_bai_viet = hit['corpus_id']      # Vị trí bài viết trong danh sách texts
        diem_tuong_dong = hit['score']         # Điểm càng gần 1.0 thì càng giống
        noi_dung = texts[vitri_bai_viet]

        print(f" Top {i+1} | Độ trùng khớp: {diem_tuong_dong:.4f}")
        print(f"Nội dung: {noi_dung[:250]}...\n")

 Top 1 | Độ trùng khớp: 0.2855
Nội dung: Nguyên Vũ  là ca sĩ, diễn viên và MC nổi tiếng. Anh tham gia nghệ thuật từ năm 1990, từ khi học trung học phổ thông đã dự liên hoan ca nhạc và từng đoạt giải A năm 1993. Đến năm 1995, anh đã trở thành ca sĩ độc quyền cho trung tâm băng đĩa nhạc Vafac...

 Top 2 | Độ trùng khớp: 0.2147
Nội dung: Nguyễn Văn Chung là một nhạc sĩ nổi tiếng với nhiều bản hit hay. Anh cũng là người ghi tên mình vào sách kỷ lục khi trở thành “Nhạc sĩ trẻ sáng tác nhiều bài hát thiếu nhi nhất Việt Nam” - với khoảng 300 ca khúc. Mới đây, nam nhạc sĩ bất ngờ khoe khô...

 Top 3 | Độ trùng khớp: 0.2076
Nội dung: Dương Triệu Vũ là nam ca sĩ nổi tiếng với hàng loạt bản hit được giới trẻ yêu mến. Trong sự nghiệp của mình, nam ca sĩ từng được biết đến là một trong những ngôi sao song ca ăn ý với Đàm Vĩnh Hưng trên sân khấu. Anh cũng là một trong những ngôi sao c...

 Top 4 | Độ trùng khớp: 0.2039
Nội dung: Nam MC, diễn viên, ca sĩ Ngô Kiến Huy bắt đầu hoạt động showbiz từ năm 2018. Sau nhiều năm, anh tạo dựng được tên tuổi của mình ở nhiều vai trò khác nhau. Hiện anh là một trong những nghệ sĩ được săn đón ở showbiz Việt. Ngô Kiến Huy vừa tậu thêm một ...

 Top 5 | Độ trùng khớp: 0.2011
Nội dung: Đất nền là một trong những phân khúc chịu “cú đòn” đau nhất từ dịch COVID-19, nhưng sản phẩm này lại ghi nhận tốc độ phục hồi mạnh mẽ trên thị trường. Bằng chứng là, khi làn sóng COVID-19 lần thứ 4 ập đến, đất nền là phân khúc chứng kiến sự sụt giảm ...

In [33]:

query("Ca sĩ", top_k=5)
print("\n")
query("Pháp Luật", top_k=5)

 Top 1 | Độ trùng khớp: 0.2855
Nội dung: Nguyên Vũ  là ca sĩ, diễn viên và MC nổi tiếng. Anh tham gia nghệ thuật từ năm 1990, từ khi học trung học phổ thông đã dự liên hoan ca nhạc và từng đoạt giải A năm 1993. Đến năm 1995, anh đã trở thành ca sĩ độc quyền cho trung tâm băng đĩa nhạc Vafac...

 Top 2 | Độ trùng khớp: 0.2147
Nội dung: Nguyễn Văn Chung là một nhạc sĩ nổi tiếng với nhiều bản hit hay. Anh cũng là người ghi tên mình vào sách kỷ lục khi trở thành “Nhạc sĩ trẻ sáng tác nhiều bài hát thiếu nhi nhất Việt Nam” - với khoảng 300 ca khúc. Mới đây, nam nhạc sĩ bất ngờ khoe khô...

 Top 3 | Độ trùng khớp: 0.2076
Nội dung: Dương Triệu Vũ là nam ca sĩ nổi tiếng với hàng loạt bản hit được giới trẻ yêu mến. Trong sự nghiệp của mình, nam ca sĩ từng được biết đến là một trong những ngôi sao song ca ăn ý với Đàm Vĩnh Hưng trên sân khấu. Anh cũng là một trong những ngôi sao c...

 Top 4 | Độ trùng khớp: 0.2039
Nội dung: Nam MC, diễn viên, ca sĩ Ngô Kiến Huy bắt đầu hoạt động showbiz từ năm 2018. Sau nhiều năm, anh tạo dựng được tên tuổi của mình ở nhiều vai trò khác nhau. Hiện anh là một trong những nghệ sĩ được săn đón ở showbiz Việt. Ngô Kiến Huy vừa tậu thêm một ...

 Top 5 | Độ trùng khớp: 0.2011
Nội dung: Đất nền là một trong những phân khúc chịu “cú đòn” đau nhất từ dịch COVID-19, nhưng sản phẩm này lại ghi nhận tốc độ phục hồi mạnh mẽ trên thị trường. Bằng chứng là, khi làn sóng COVID-19 lần thứ 4 ập đến, đất nền là phân khúc chứng kiến sự sụt giảm ...



 Top 1 | Độ trùng khớp: 0.3078
Nội dung: Luật pháp về đất đai là công cụ pháp lý để Nhà nước quản lý đất đai chặt chẽ hơn, những năm qua, pháp luật về đất đai liên tục được hoàn thiện và đã có những đóng góp quan trọng vào nguồn lực phát triển kinh tế - xã hội, nhất là ở các địa phương. Luậ...

 Top 2 | Độ trùng khớp: 0.2596
Nội dung: Đánh bạc là hành vi trái pháp luật. Nếu phát hiện, công dân có trách nhiệm thông báo cho cơ quan chức năng để kịp thời ngăn chặn, xử lý. Theo đó, nếu chủ trọ biết được có người thuê nhà tổ chức đánh bạc trái phép nhưng không khai báo với cơ quan Công...

 Top 3 | Độ trùng khớp: 0.2462
Nội dung: Vừa qua, đã có các ý kiến quan ngại của nhiều đại biểu Quốc hội đối với nội dung đề xuất sửa đổi, bổ sung điểm c khoản 1 Điều 75 Luật Đầu tư 2020 và sửa đổi, bổ sung khoản 1 Điều 23 Luật Nhà ở 2014 cần được quan tâm xem xét, lý giải thật thấu đáo khi...

 Top 4 | Độ trùng khớp: 0.2437
Nội dung: Điều 153 Luật Nhà ở 2014 quy định, việc cho mượn, cho ở nhờ nhà ở thuộc sở hữu chung hợp nhất phải được sự đồng ý của tất cả các chủ sở hữu nhà ở đó.  Trường hợp chủ sở hữu nhà ở thuộc sở hữu chung theo phần thì có quyền cho mượn, cho ở nhờ thuộc phầ...

 Top 5 | Độ trùng khớp: 0.2406
Nội dung: Tại Điều 6 Luật Đất đai 2013 đã quy định về nguyên tắc sử dụng đất như sau: - Đúng quy hoạch, kế hoạch sử dụng đất và đúng mục đích sử dụng đất. - Tiết kiệm, có hiệu quả, bảo vệ môi trường và không làm tổn hại đến lợi ích chính đáng của người sử dụng...